# Setup
title:    AnayDis
tagline:  An치lisis y Dise침o de Algoritmos
baseurl:  /anaydis
zip:	    https://github.com/FacultadDeIngenieria/anaydis/zipball/gh-pages

# About/contact
author:
name:       An치lisis y Dise침o de Algoritmos
